#!/bin/bash

# ask a question. If the user answers "y", everything is fine. Otherwise exit 12
function question {
	echo -n "$1 (\"y\" if ok) "
	local ANSWER
	read ANSWER
	case "${ANSWER}" in
	  y) : ;;
	  *) exit 12 ;;
	esac
}

# return the name of the branch we are in. Get it with: local B = $(getBranchName)
function getBranchName {
	local BRANCH=$(git rev-parse --abbrev-ref HEAD)
	echo "${BRANCH}"
	return 0
}
	
# check whether the branch checked out is clean. If not exit 12
function checkBranchClean {
	if [ -z "$(git status --porcelain)" ];
	then
		:
	else
		echo "please commit your changes. Exit 12"
		exit 12
	fi
}

function get_toml() {
  python - "$1" "$property_file" <<'PY'
import sys, pathlib, json
key, file = sys.argv[1], sys.argv[2]
p = pathlib.Path(file)
try:
    import tomllib as tl
    data = tl.loads(p.read_text())
except Exception:
    import toml as tl
    data = tl.load(p)
cur = data
for part in key.split('.'):
    if isinstance(cur, dict) and part in cur:
        cur = cur[part]
    else:
        print("", end="")
        sys.exit(0)
if isinstance(cur, (dict, list)):
    print(json.dumps(cur))
else:
    print(cur)
PY
}

# make a docker image of one of the examples stored in directory 'test/container'. Structure:
# test/container
#  domain (e.g. sklearn)
#    name (e.g. train)
function make_image {
    domain=$1
    name=$2
    version=$3

    tag="${domain}_${name}:${version}"

    echo "building docker image $tag"

    if [[ -z "$domain" ]]; then
        echo "Error: domain name missing. Exit 12"
        exit 12
    fi
    if [[ -z "$name" ]]; then
        echo "Error: docker image name missing. Exit 12"
        exit 12
    fi
    if [[ -z "$version" ]]; then
        echo "Error: version missing. Exit 12"
        exit 12
    fi

    cd $BASE_DIR/test/container/$domain/$name
    docker build . -t $tag
}

# check the Python implementation for vulnerabilities and licences of used packages
function run_assess {
    uv sync
    uv lock
    uv run pip-audit -f json | python -m json.tool >audit.json
    uv run pip-licenses --from=mixed --format=json | python -m json.tool >licenses.json
    uv run pip-licenses --from=mixed --format=markdown --output-file=licenses.md
}

# get the name of the underlying os
function getOS {
    OS=${OSTYPE//[0-9.-]*/}
    case "$OS" in
      linux)  echo "linux" ;;
      darwin) echo "macos" ;;
      msys)   echo "win" ;;
      *)      echo "UNKNOWN" ;;
    esac
}

function isWin {
    [ $(getOS) == 'win' ]
}

function isLinux {
    [ $(getOS) == 'linux' ]
}

# make absolute path. Should work on both linux and windows with git bash 
function make_absolute_path() {
    local path="$1"
    # Check if already absolute (Unix or Windows style)
    if [[ "$path" = /* ]] || [[ "$path" =~ ^[a-zA-Z]: ]]; then
        # For Windows paths in Git Bash, convert to proper format
        if $(isWin); then
            echo "$(cygpath -m "$path")"
        else
            echo "$path"
        fi
    else
        # Make relative path absolute
        if $(isWin); then
            echo "$(cygpath -m "$(pwd)/$path")"
        else
            echo "$(pwd)/$path"
        fi
    fi
}

# get a path property from the toml configuration file and make it an absolute path as needed the host operating system 
function get_toml_and_make_absolute_path {
    local path="$1"
    path=$(get_toml "$path")
    echo $(make_absolute_path "$path")
}

# activate the virtual environment.venv generated by uv
function activate_env {
    if $(isLinux)
    then
        source .venv/bin/activate
    fi
    if $(isWin)
    then
        source .venv/Scripts/activate
    fi
}

function init_dir {
    dir="$1"
    is_es="$2"
    if [[ -d "$dir" ]]
    then
        echo "directory $dir exists - no init needed"
    else
        mkdir -p $dir
    fi
    if [[ -z "$is_es" ]]
    then
        :
    else
        if [[ -f "$dir/user.json" ]]
        then
            echo "entities in $dir exist - no init needed"
        else
            cp -r $BASE_DIR/initdata/* $dir
        fi
    fi
}

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$1" == '-q' ]];
then
    shift
else
    echo "run '$0 --help' to see available commands of this bash script"
fi

while [[ $# -gt 0 ]]; do
    cmd="$1"; shift

    case "$cmd" in
    ''|-h|--help)     cat admin-help.txt ;;

    --test)           echo $(get_toml 'server.host')
                      echo $(get_toml 'server.port') ;;

    --backend)        case "$1" in
                        --*|'') property_file='./parma_light.toml' ;;
                        -c)     property_file="$2"; shift; shift ;;
                        *)      echo "invalid parameter $1 for --backend - exit 12"
                                exit 12 ;;
                      esac
                      if $(isLinux)
                      then
                          HOSTOS='linux'
                      fi
                      if $(isWin)
                      then
                          HOSTOS='windows'
                      fi
                      export HOST_OPERATING_SYSTEM=$HOSTOS
                      python src/parma/backend.py -c $property_file
                      exit 0 ;;

    --frontend)       case "$1" in
                        --*|'') property_file='./parma_light.toml' ;;
                        -c)     property_file="$2"; shift; shift ;;
                        *)      echo "invalid parameter $1 for --frontend - exit 12"
                                exit 12 ;;
                      esac
                      python src/parma/frontend_cli.py -c $property_file
                      exit 0 ;;

    --init)           PARMA_DIR='./datastore_parma'
                      if [[ -d ./.git && -d ./src/parma ]]
                      then
                          echo "$PARMA_DIR is a test directory and will be emptied if it exists"
                          rm -rf $PARMA_DIR
                          mkdir -p $PARMA_DIR/entity_store $PARMA_DIR/data_dir $PARMA_DIR/temp_dir
                          cp -r $BASE_DIR/initdata/* $PARMA_DIR/entity_store
                          echo "parma initialized in directory '$PARMA_DIR'"
                          cd $BASE_DIR
                      else
                          echo 'init_local only works toplevel in a parma_light git repo'
                      fi ;;

    --image)          domain=$1; shift
                      name="$1"; shift
                      version="$1"; shift
                      make_image $domain $name $version ;;

    --images)         domain=$1; shift
                      cd $BASE_DIR/test/container/$domain
                      for dir in */; do
                          dir_name="${dir%/}"
                          $BASE_DIR/admin.sh -q --image "$domain" "$dir_name" "1"
                      done ;;

    # run parma-light in a container
    # 1. build the image
    # 2. run the image
    # 3. script to be executed in the container
    --dood-build)     docker build -f docker/Dockerfile -t parma_light . ;;

    --dood-run)       docker_image='parma_light'
                      debugpy=''
                      property_file='./parma_light.toml'
                      while [[ 1 ]]; do
                        case "$1" in
                          --*|'')   break ;;
                          -di)      docker_image="$2"; shift; shift ;;
                          -c)       property_file="$2"; shift;shift ;;
                          -debugpy) debugpy=' -p 5678:5678'; shift ;;
                          *)        echo "invalid parameter $1 for --dood-run - exit 12"
                                    exit 12 ;;
                        esac
                      done
                      export property_file=$(make_absolute_path $property_file)

                      type=$(get_toml 'store.type')
                      if [ "$type" = 'dood' ]
                      then
                        :
                      else
                        echo "type in store section of toml property file must be 'dood' for --dood-run - exit 12"
                        exit 12
                      fi

                      entity_store=$(get_toml_and_make_absolute_path 'store.entity_store'); init_dir $entity_store 'es'
                      data_dir=$(get_toml_and_make_absolute_path 'store.data_dir');         init_dir $data_dir
                      temp_dir=$(get_toml_and_make_absolute_path 'store.temp_dir');         init_dir $temp_dir
                      log_file=$(get_toml_and_make_absolute_path 'store.log_file');         mkdir -p $(dirname $log_file); touch $log_file
                      base_dir=$(get_toml_and_make_absolute_path 'store.base_dir')

                      cmd="docker run --name parma_light --rm -it -p 8080:8080"
                      cmd+="$debugpy"
                      if $(isLinux)
                      then
                          cmd+=' -v /var/run/docker.sock:/var/run/docker.sock'
                          cmd+=' -e HOST_OPERATING_SYSTEM=linux'
                      fi
                      if $(isWin)
                      then
                          cmd+=' -v //var/run/docker.sock:/var/run/docker.sock'
                          cmd+=' -e HOST_OPERATING_SYSTEM=windows'
                      fi
                      cmd+=" -v $property_file:/app/parma_light.toml"
                      cmd+=" -v $entity_store:/entity_store"
                      cmd+=" -v $data_dir:/data_dir -e PARMA_LIGHT_DATA_DIR_HOST=\"$data_dir\""
                      cmd+=" -v $temp_dir:/temp_dir -e PARMA_LIGHT_TEMP_DIR_HOST=\"$temp_dir\""
                      cmd+=" -v $log_file:/app/parma_light.log"
                      cmd+=" -v $base_dir:/base_dir"
                      cmd+=" $docker_image"
                      if [[ "$debugpy" != '' ]]
                      then
                        cmd+=" --debugpy"
                      fi
                      echo "executing: $cmd"
                      eval $cmd
                      exit 0 ;;

    --dood-script)    activate_env
                      python src/parma/backend.py $@
                      exit 0 ;;
    
    --assess)         run_assess ;;

    --publish-new-version) checkBranchClean
                      B=$(getBranchName)
                      case "$B" in
                        master) : ;;
                        *)      question "do you really want to push a tag to github from branch '$B'?" ;;
                      esac
                      version="$1"
                      case "$version" in
                        v*) : ;;
                        *)  echo "a new version name must be given and start with 'v' - exit 12"
                            exit 12 ;;
                      esac
                      shift
                      git tag "$version"
                      git push origin "$version"
                      echo "created and pushed tag '$version'. A github action will create the image and push to docker hub" ;; 

    *)                echo "invalid command: $cmd - exit 12"
                      exit 12 ;;
    esac
done

exit 0