#!/bin/bash

# ask a question. If the user answers "y", everything is fine. Otherwise exit 12
function question {
	echo -n "$1 (\"y\" if ok) "
	local ANSWER
	read ANSWER
	case "${ANSWER}" in
	  y) : ;;
	  *) exit 12 ;;
	esac
}

# return the name of the branch we are in. Get it with: local B = $(getBranchName)
function getBranchName {
	local BRANCH=$(git rev-parse --abbrev-ref HEAD)
	echo "${BRANCH}"
	return 0
}
	
# check whether the branch checked out is clean. If not exit 12
function checkBranchClean {
	if [ -z "$(git status --porcelain)" ];
	then
		:
	else
		echo "please commit your changes. Exit 12"
		exit 12
	fi
}

# init the data store of parma_light
function init {
    PARMA_DIR="$1"
    if [[ $PARMA_DIR == '' ]]
    then
        PARMA_DIR='datastore_parma'
        if [[ -d $PARMA_DIR/entity_store && -d $PARMA_DIR/data_dir && -d $PARMA_DIR/temp_dir ]]
        then
            echo "datastore_parma seems to be a test directory and will be emptied"
            rm -rf $PARMA_DIR
        fi
    fi
    
    if [[ -d $PARMA_DIR/entity_store || -d $PARMA_DIR/data_dir || -d $PARMA_DIR/temp_dir ]]
    then
        echo "data in parma datastore '$PARMA_DIR' found"
    else
        mkdir -p $PARMA_DIR/entity_store $PARMA_DIR/data_dir $PARMA_DIR/temp_dir
        cp -r $BASE_DIR/initdata/* $PARMA_DIR/entity_store
        echo "parma initialized in directory '$PARMA_DIR'"
        cd $BASE_DIR
    fi
}

# make a docker image of one of the examples stored in directory 'test/container'. Structure:
# test/container
#  domain (e.g. sklearn)
#    name (e.g. train)
function make_image {
    domain=$1
    name=$2
    version=$3

    tag="${domain}_${name}:${version}"

    echo "building docker image $tag"

    if [[ -z "$domain" ]]; then
        echo "Error: domain name missing. Exit 12"
        exit 12
    fi
    if [[ -z "$name" ]]; then
        echo "Error: docker image name missing. Exit 12"
        exit 12
    fi
    if [[ -z "$version" ]]; then
        echo "Error: version missing. Exit 12"
        exit 12
    fi

    cd $BASE_DIR/test/container/$domain/$name
    docker build . -t $tag
}

# check the Python implementation for vulnerabilities and licences of used packages
function run_assess {
    uv sync
    uv lock
    uv run pip-audit -f json | python -m json.tool >audit.json
    uv run pip-licenses --from=mixed --format=json | python -m json.tool >licenses.json
    uv run pip-licenses --from=mixed --format=markdown --output-file=licenses.md
}

# get the name of the underlying os
function getOS {
    OS=${OSTYPE//[0-9.-]*/}
    case "$OS" in
      linux)  echo "linux" ;;
      darwin) echo "macos" ;;
      msys)   echo "win" ;;
      *)      echo "UNKNOWN" ;;
    esac
}

function isWin {
    [ $(getOS) == 'win' ]
}

function isLinux {
    [ $(getOS) == 'linux' ]
}

# activate the virtual environment.venv generated by uv
function activate_env {
    if $(isLinux)
    then
        source .venv/bin/activate
    fi
    if $(isWin)
    then
        source .venv/Scripts/activate
    fi
}

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$1" == '-q' ]];
then
    shift
else
    echo "run '$0 help' to see available commands of this bash script"
fi

while [[ $# -gt 0 ]]; do
    cmd="$1"; shift

    case "$cmd" in
    ''|'-h'|'--help') cat admin-help.txt ;;

    --backend)        python src/parma/backend.py ;;

    --frontend)       python src/parma/frontend_cli.py ;;

    --init)           dir="$1"
                      case "$dir" in
                      --*) init '' ;;
                      '')  init '' ;;
                      *)   shift
                           init "$dir" ;;
                      esac ;;
    --image)          domain=$1; shift
                      name="$1"; shift
                      version="$1"; shift
                      make_image $domain $name $version ;;

    --images)         domain=$1; shift
                      cd $BASE_DIR/test/container/$domain
                      for dir in */; do
                          dir_name="${dir%/}"
                          $BASE_DIR/admin.sh -q --image "$domain" "$dir_name" "1"
                      done ;;

    # run parma-light in a container
    # 1. build the image
    # 2. run the image
    # 3. script to be executed in the container
    --dind-build)     docker build --no-cache -f docker/Dockerfile -t parma_light . ;;

    --dind-run)       docker_image='parma_light'
                      datastore_mount=''
                      logfile_mount=''
                      while [[ 1 ]]; do
                        sub_cmd="$1"
                        case "$sub_cmd" in
                          --*|'') break ;;
                          -di)    docker_image="$2"; shift; shift ;;
                          -ds)    datastore_mount=" -v $2:/app/datastore_parma"; shift; shift ;;
                          -log)   touch $2; logfile_mount=" -v $2:/app/parma_light.log"; shift; shift ;;
                          *)      echo 'invalid parameter for --dind-run - exit 12'
                                  exit 12 ;;
                        esac
                      done
                      if $(isLinux)
                      then
                          socket_mount='/var/run/docker.sock:/var/run/docker.sock'
                      fi
                      if $(isWin)
                      then
                          socket_mount='//var/run/docker.sock:/var/run/docker.sock'
                      fi
                      cmd="docker run -p 8080:8080 -v $socket_mount$datastore_mount$logfile_mount -ti $docker_image"
                      echo "executing: $cmd"
                      eval $cmd ;;

    --dind-script)    init /app/datastore_parma
                      activate_env
                      python src/parma/backend.py ;;
    
    --assess)         run_assess ;;

    --push-tag)       checkBranchClean
                      B=$(getBranchName)
                      case "$B" in
                        master) : ;;
                        *)      question "do you really want to push a tag to github from branch '$B'?" ;;
                      esac
                      version="$1"
                      case "$version" in
                        v*) : ;;
                        *)  echo "a tag name must be given and start with 'v' - exit 12"
                            exit 12 ;;
                      esac
                      shift
                      git tag "$version"
                      git push origin "$version"
                      echo "created and pushed tag '$version'" ;; 

    *)                echo "invalid command: $cmd - exit 12"
                      exit 12 ;;
    esac
done

exit 0