#!/bin/bash

# get the name of the underlying os
function getOS {
    OS=${OSTYPE//[0-9.-]*/}
    case "$OS" in
      linux)  echo "linux" ;;
      darwin) echo "macos" ;;
      msys)   echo "win" ;;
      *)      echo "UNKNOWN" ;;
    esac
}

function isWin {
    [ $(getOS) == 'win' ]
}

function isLinux {
    [ $(getOS) == 'linux' ]
}

# activate the virtual environment.venv generated by uv
function activate_env {
    if $(isLinux)
    then
        source .venv/bin/activate
    elif $(isWin)
    then
        source .venv/Scripts/activate
    fi
}

activate_env
python src/parma/backend.py $@